Streaming/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Configuration;
using System.Threading;
using System.Web.Routing;
using System.Globalization;

using Streaming.App_Start;
using Streaming.Clients;
using Streaming.ViewModels;

using StreamingAssemblies.DataAccess;
using StreamingAssemblies.Models.QuoVadis.Pessoas;
using Streaming.Helpers;

namespace Streaming.Controllers
{
    public class BaseController : Controller
    {
        private readonly StreamingService _streamingService = new StreamingService(ConfigurationManager.ConnectionStrings["streamingDBString"].ConnectionString);

        private readonly IUTADClient _iUTADClient = new IUTADClient();
        private readonly MensagensClient _mensagensClient = new MensagensClient();

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);

            // Se os idiomas suportados ainda não foram obtidos, obtém esses idiomas do QuoVadis
            if (StreamingSession.Session.Linguagens.Count == 0)
            {
                bool success = Apresentacao.LoadSupportedLinguagens();

                if (success == true)
                {
                    try
                    {
                        var symbols = HttpHelper.GetLanguageSymbols(Request, "pt-PT");
                        
                        success = Apresentacao.LoadLinguagem(symbols);
                    }
                    catch (Exception e)
                    {
                        //TODO: log this
                    }

                    if (success == true)
                    {
                        Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(StreamingSession.Session.SelectedLinguagem.Symbol);
                        Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo(StreamingSession.Session.SelectedLinguagem.Symbol);

                        success = Apresentacao.LoadApresentacaoData();
                    }
                }

                if (success == false)
                {
                    TempData["error"] = "Ocorreu um erro ao carregar informação!";
                }
            }
        }

        // Esta é a função principal que é executada sempre que uma página é carregada no Streaming
        // Obtém os elementos HTML autorizados para apresentar na página, bem como as mensagens mais recentes tanto locais como provenientes do QuoVadis
        protected override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            base.OnActionExecuted(filterContext);

            // Só executa o código apenas quando uma view totalmente nova é retornada
            // Sem isto, todo este código é efectuado para qualquer coisa retornada - views, partial views, redirects, etc.
            if (filterContext.Result.GetType() == typeof(ViewResult))
            {
                BaseViewModel layoutModel = new BaseViewModel();

                if (Convert.ToBoolean(ConfigurationManager.AppSettings["Aplicacao.Mensagens"]) == true)
                {
                    // Obtém todas as mensagens a apresentar
                    // Começa por obter as mensagens locais da aplicação, que se encontram armazenadas na base de dados do Streaming
                    int mensagensDashboardVisibilidade = 0;

                    if (Autenticacao.IsLoggedIn() == true)
                    {
                        mensagensDashboardVisibilidade = 2;
                    }
                    else
                    {
                        mensagensDashboardVisibilidade = 3;
                    }

                    layoutModel.MensagensList.AddRange(_streamingService.NSI_STP_Mensagens_S_ByVisibilidade(mensagensDashboardVisibilidade));

                    // Depois obtém as mensagens globais, que são definidas a partir do QuoVadis
                    string perfisPublicacao = "''";
                    string tiposCargosPublicacao = "''";
                    string orgaosPublicacao = "''";
                    string usernamePublicacao = "''";

                    if (Autenticacao.IsLoggedIn() == true)
                    {
                        perfisPublicacao = string.Join(";", StreamingSession.Session.Perfis.Where(sp => sp.Ativo == true).Select(p => p.Tipo).Distinct());
                        tiposCargosPublicacao = string.Join(";", StreamingSession.Session.Cargos.Select(p => p.CodigoTipoCargo).Distinct());
                        orgaosPublicacao = string.Join(";", StreamingSession.Session.Cargos.Select(p => p.CodigoOrgao).Distinct());
                        usernamePublicacao = StreamingSession.Session.Username;

                        if (perfisPublicacao == "")
                        {
                            perfisPublicacao = "''";
                        }

                        if (tiposCargosPublicacao == "")
                        {
                            tiposCargosPublicacao = "''";
                        }

                        if (orgaosPublicacao == "")
                        {
                            orgaosPublicacao = "''";
                        }
                    }

                    layoutModel.MensagensList.AddRange(_mensagensClient.GetMensagensByVisibilidades(perfisPublicacao, tiposCargosPublicacao, orgaosPublicacao, usernamePublicacao));
                }

                if (Autenticacao.IsLoggedIn() == true)
                {
                    // Carrega os elementos HTML autorizados para o utilizador autenticado
                    // Primeiro verifica se o mecanismo de autorizações está ativado para o Streaming
                    layoutModel.IsAutorizacoesEnabled = Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.Autorizacoes"]);

                    if (layoutModel.IsAutorizacoesEnabled == true)
                    {
                        // Da lista de elementos HTML autorizados guardada previamente na sessão do browser, obtém e guarda aqueles que correspondem à página a ser carregada
                        string autorizacoesCurrentURL = RouteData.Values["controller"].ToString() + "/" + RouteData.Values["action"].ToString();

                        layoutModel.AutorizacoesList.AddRange(StreamingSession.Session.Autorizacoes.Where(a => a.Pagina == autorizacoesCurrentURL).ToList());
                    }
                }

                filterContext.Controller.ViewData["LayoutModel"] = layoutModel;
            }
        }

        public ActionResult ChangeLinguagem(string symbol)
        {
            bool success = Apresentacao.LoadLinguagem(symbol);

            if (success == true)
            {
                Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(StreamingSession.Session.SelectedLinguagem.Symbol);
                Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo(StreamingSession.Session.SelectedLinguagem.Symbol);

                success = Apresentacao.LoadApresentacaoData();
            }

            if (success == false)
            {
                TempData["error"] = "Ocorreu um erro ao carregar informação!";
            }

            return Redirect(Request.UrlReferrer.AbsoluteUri);
        }

        public ActionResult LoadProfilePartial()
        {
            return PartialView("_ProfilePartial");
        }

        public ActionResult SearchPessoas(string searchQuery)
        {
            List<Pessoa> pessoasList = _iUTADClient.SearchPessoas(2, searchQuery);

            return PartialView("_MenuLateralSearchPessoasPartial", pessoasList);
        }
    }
}

Streaming/Controllers/SecureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Streaming.Controllers
{
    public class SecureController : BaseController
    {
        public ActionResult Index()
        {
            if (Request.ServerVariables["HTTP_REMOTEUSER"] != null)
            {
                if (Session["erroAutenticacao"] != null)
                {
                    TempData["error"] = Session["erroAutenticacao"].ToString();
                }
                else
                {
                    Session["shib"] = Request.ServerVariables["HTTP_REMOTEUSER"].ToString();

                    if (Session["returnURL"] != null)
                        return Redirect(Session["returnURL"].ToString());
                }

                return RedirectToAction("Index", "Home");
            }

            return View();
        }
    }
}

Streaming/Views/Shared/_AlertsPartial.cshtml
@if (TempData["warning"] != null && string.IsNullOrEmpty(TempData["warning"].ToString()) == false)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">
            <span class="fa fa-exclamation-triangle"></span>
            Aviso!
        </h4>
        @TempData["warning"]

        <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (TempData["success"] != null && string.IsNullOrEmpty(TempData["success"].ToString()) == false)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">
            <span class="fa fa-check-circle"></span>
            Sucesso!
        </h4>
        @TempData["success"]

        <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (TempData["info"] != null && string.IsNullOrEmpty(TempData["info"].ToString()) == false)
{
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">
            <span class="fa fa-info-circle"></span>
            Informação
        </h4>
        @TempData["info"]

        <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (TempData["error"] != null && string.IsNullOrEmpty(TempData["error"].ToString()) == false)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert" aria-label="Fechar">
        <h4 class="alert-heading">
            <span class="fa fa-exclamation-circle"></span>
            Erro!
        </h4>
        @TempData["error"]

        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

Streaming/Views/Shared/_Layout.cshtml
@using System.Configuration;

@using Streaming.App_Start;

@{
    //string appTitle = ConfigurationManager.AppSettings["Aplicacao.Titulo"];

    //ViewBag.Title = ViewBag.Title ?? appTitle;
    
    string appTitle = ConfigurationManager.AppSettings["Aplicacao.Titulo"];

    if (ViewBag != null)
    {
        ViewBag.Title = ViewBag.Title ?? appTitle;
    }
}

<!doctype html>
<html xmlns="https://www.w3.org/1999/xhtml" lang="@StreamingSession.Session.SelectedLinguagem.Symbol">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=9,IE=10,IE=11" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <title>@ViewBag.Title</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />

    <!-- jQuery library -->
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>

    <!-- Popper.JS library -->
    <script src="~/Scripts/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="~/Scripts/bootstrap.min.js"></script>

    <!-- ProgressBar.js library -->
    <script src="~/Scripts/progressBar.min.js"></script>

    @Styles.Render("~/Content/theme/all.css")

    <link rel="shortcut icon" href="~/favicon.ico?v=3" />

    <script>
        $(document).ready(function () {
            var bar = new ProgressBar.Line(streamingProgressBarContainer, {
                strokeWidth: 4,
                easing: "easeInOut",
                duration: 1400,
                color: "@StreamingSession.Session.AplicacaoPortalBase.CorPortalBase",
                trailColor: "white",
                trailWidth: 1,
                svgStyle: {
                    width: '100%',
                    height: '100%'
                }
            });

            bar.animate(1.0);

            $.get("@Url.Action("LoadProfilePartial", "Base")", function (data) {
                $("[data-toggle='popover']").popover({
                    container: "body",
                    trigger: "focus",
                    template: '<div class="popover portalbase-navbar-profile" role="tooltip"><div class="arrow"></div><h3 class="popover-header"></h3><div class="popover-body"></div></div>',
                    html: true,
                    content: data
                });
            });

            $('#streamingSidebarCollapse').click(function () {
                $('#streamingSidebar').toggleClass('active');
            });

            $("#searchPessoas").click(function () {
                var searchQuery = $("#searchPessoasSearchQuery").val();

                if (searchQuery != "") {
                    $("#searchPessoas").prop("disabled", true);
                    $("#searchPessoasButtonIcon").removeClass("fa fa-search").addClass("fa fa-circle-o-notch fa-spin");

                    $("#searchPessoasModalContent").load("@Url.Action("SearchPessoas", "Base")", { searchQuery: searchQuery }, function () {
                        $("#searchPessoasModal").modal("show");

                        $("#searchPessoasButtonIcon").removeClass("fa fa-circle-o-notch fa-spin").addClass("fa fa-search");
                        $("#searchPessoas").prop("disabled", false);
                    });
                }
            });
        });
    </script>
</head>
<body>
    <nav class="navbar navbar-expand-lg portalbase-navbar">
        @if (Autenticacao.IsLoggedIn() == true && (StreamingSession.Session.MenuLateral.Count > 0 || StreamingSession.Session.AplicacoesPortalBaseMenuLateral.Count > 0))
        {
            <span id="streamingSidebarCollapse" class="portalbase-navbar-sidebar-toggle">
                <img src=@Url.Content("~/Content/Images/menuresponsiveicon.png")>
            </span>
        }

        <a href="@Url.Action("Index", "Home")" class="portalbase-app-square small" style="background-color: @StreamingSession.Session.AplicacaoPortalBase.CorPortalBase">
            <span>@StreamingSession.Session.AplicacaoPortalBase.SiglaPortalBase</span>
        </a>

        <span class="navbar-brand mr-auto portalbase-navbar-apptitle"><a href="@Url.Action("Index", "Home")">@appTitle</a></span>

        <ul class="navbar-nav ml-auto">
            @if (Autenticacao.IsLoggedIn() == true)
            {
                <li class="nav-item">
                    <span class="fa fa-user fa-2x portalbase-navbar-icon" tabindex="0" data-toggle="popover" data-placement="bottom"></span>
                </li>

                <li class="nav-item">
                    <a class="nav-link portalbase-navbar-loginbutton" href="@Url.Action("Logout", "Session")" style="background-color: @StreamingSession.Session.AplicacaoPortalBase.CorPortalBase;">
                        Terminar Sessão
                    </a>
                </li>
            }
            else
            {
                <li class="nav-item">
                    @if (Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.UTAD.Shibboleth"]) == true)
                    {
                        <a class="nav-link portalbase-navbar-loginbutton" href="@Url.Action("Index", "Secure")" style="background-color: @StreamingSession.Session.AplicacaoPortalBase.CorPortalBase;">
                            Iniciar Sessão
                        </a>
                    }
                    else
                    {
                        <a class="nav-link portalbase-navbar-loginbutton" href=@Url.Action("Login", "Session") style="background-color: @StreamingSession.Session.AplicacaoPortalBase.CorPortalBase;">
                            Iniciar Sessão
                        </a>
                    }
                </li>
            }

            @if (StreamingSession.Session.Linguagens.Count > 0)
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle portalbase-navbar-linguagens" title="@StreamingSession.Session.SelectedLinguagem.Titulo" href="#" role="button" data-toggle="dropdown">
                        @StreamingSession.Session.SelectedLinguagem.Ref
                    </a>
                    <div class="dropdown-menu portalbase-navbar-linguagens-menu">
                        @foreach (StreamingAssemblies.Models.QuoVadis.Aplicacoes.Linguagem item in StreamingSession.Session.Linguagens.Where(l => l.Symbol != StreamingSession.Session.SelectedLinguagem.Symbol))
                        {
                            <a class="dropdown-item" title="@item.Titulo" href="@Url.Action("ChangeLinguagem", "Base", new { symbol = item.Symbol })">
                                @item.Ref
                            </a>
                        }
                    </div>
                </li>
            }
        </ul>
    </nav>

    <div id="streamingProgressBarContainer" class="portalbase-progressbar-container"></div>

    <div class="d-flex">
        @if (Autenticacao.IsLoggedIn() == true && (StreamingSession.Session.MenuLateral.Count > 0 || StreamingSession.Session.AplicacoesPortalBaseMenuLateral.Count > 0))
        {
            <nav id="streamingSidebar" class="portalbase-sidebar">
                @*<a title="Dashboard" href="https://quovadis.utad.pt/Dashboard/" class="list-group-item list-group-item-action">
                    <span class="fa fa-user-circle-o"></span>
                    Dashboard
                    <span class="fa fa-angle-right"></span>
                </a>*@

                <div class="input-group">
                    <input id="searchPessoasSearchQuery" type="text" class="form-control" placeholder="pessoas.utad.pt">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="searchPessoas">
                            <span id="searchPessoasButtonIcon" class="fa fa-search"></span>
                        </button>
                    </div>
                </div>

                @if (StreamingSession.Session.MenuLateral.Count > 0)
                {
                    <div class="list-group">
                        @{
                            Html.RenderPartial("_MenuLateralPartial", StreamingSession.Session.MenuLateral);
                        }
                    </div>

                    <br />
                }

                @if (StreamingSession.Session.AplicacoesPortalBaseMenuLateral.Count > 0)
                {
                    <div class="list-group">
                        @{
                            Html.RenderPartial("_MenuLateralPartial", StreamingSession.Session.AplicacoesPortalBaseMenuLateral);
                        }
                    </div>
                }
            </nav>

            <div class="modal fade" id="searchPessoasModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-xl modal-dialog-scrollable" role="document">
                    <div id="searchPessoasModalContent" class="modal-content">

                    </div>
                </div>
            </div>
        }

        <div class="col">
            <div class="portalbase-main">
                <div id="alerts">
                    @{
                        Html.RenderPartial("_AlertsPartial");
                    }
                </div>

                @RenderBody()
            </div>

            <footer class="portalbase-footer">
                <div class="pt-1 text-muted text-center">
                    @if (Convert.ToBoolean(ConfigurationManager.AppSettings["Aplicacao.GetFooterFromQuoVadis"]) == true)
                    {
                        <span><b><small>Universidade de Trás-os-Montes e Alto Douro - NSI @DateTime.Now.Year</small></b></span> <br />
                        <a href=@Url.Content(StreamingSession.Session.Footer.LinkContatos)><b><small>&#9642; Contatos</small></b></a>
                        <a href=@Url.Content(StreamingSession.Session.Footer.LinkPolPriv)><b><small>&#9642; Política de Privacidade</small></a>
                        <div>
                            <img src=@Url.Content("https://assets.utad.pt/images/" + StreamingSession.Session.Footer.FooterImage) alt="QREN" />
                            <span>
                                <a href="https://www.w3.org/WAI/WCAG2AAA-Conformance" title="Explanation of WCAG 2.0 Level Triple-A Conformance">
                                    <img height="32" width="88" src="https://www.w3.org/WAI/wcag2AAA" alt="Level Triple-A conformance, W3C WAI Web Content Accessibility Guidelines 2.0">
                                </a>
                            </span>
                        </div>
                    }
                    else
                    {
                        <span><b><small>Universidade de Trás-os-Montes e Alto Douro - NSI @DateTime.Now.Year</small></b></span>
                        <div>
                            <img src=@Url.Content("~/Content/Images/qrenlogos.png") alt="QREN" />
                            <div>
                                <span>
                                    <a href="https://www.w3.org/WAI/WCAG2AAA-Conformance" title="Explanation of WCAG 2.0 Level Triple-A Conformance">
                                        <img height="32" width="88" src="https://www.w3.org/WAI/wcag2AAA" alt="Level Triple-A conformance, W3C WAI Web Content Accessibility Guidelines 2.0">
                                    </a>
                                </span>
                            </div>
                        </div>
                    }
                </div>
            </footer>
        </div>
    </div>
</body>
</html>

Streaming/Views/Shared/_MenuLateralPartial.cshtml
@model IEnumerable<StreamingAssemblies.Models.MenuItem>

@foreach (var item in Model)
{
    @Html.StreamingMenuItem(item);

    if (item.MenuItemChildList.Count > 0)
    {
        if (item.MenuItemChildListIsOpen == true)
        {
            <div class="list-group collapse show" id="collapseSidebar-@item.Id">
                @{
                    Html.RenderPartial("_MenuLateralPartial", item.MenuItemChildList);
                }
            </div>
        }
        else
        {
            <div class="list-group collapse" id="collapseSidebar-@item.Id">
                @{
                    Html.RenderPartial("_MenuLateralPartial", item.MenuItemChildList);
                }
            </div>
        }
    }
}

Streaming/Views/Shared/_MenuLateralSearchPessoasPartial.cshtml
@model IEnumerable<StreamingAssemblies.Models.QuoVadis.Pessoas.Pessoa>

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">
        <span class="fa fa-search"></span>
        pessoas.utad.pt - Procura
    </h5>

    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    @if (Model.Count() > 0)
    {
        <div class="list-group">
            @foreach (StreamingAssemblies.Models.QuoVadis.Pessoas.Pessoa item in Model)
            {
                <a href="@string.Concat("https://pessoas.utad.pt/detalhe.php?iupi=", item.Iupi)" class="list-group-item list-group-item-action" target="_blank">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">@item.Nome</h5>
                    </div>

                    @foreach (StreamingAssemblies.Models.QuoVadis.Pessoas.PessoaPerfil itemPerfil in item.PessoaPerfisList)
                    {
                        if (itemPerfil.VisibilidadeCategoria == 2 || itemPerfil.VisibilidadeCategoria == 3)
                        {
                            <p class="mb-1">@itemPerfil.Categoria</p>
                        }

                        if (itemPerfil.VisibilidadeUo == 2 || itemPerfil.VisibilidadeUo == 3)
                        {
                            <p class="mb-1">@itemPerfil.Uo</p>
                        }
                    }
                </a>
            }
        </div>
    }
    else
    {
        <p>Não foram encontradas pessoas da UTAD!</p>
    }
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
</div>

Streaming/Views/Shared/_ProfilePartial.cshtml
@using Streaming.App_Start;

<div class="row">
    <div class="col-md-2 portalbase-navbar-profile-foto">
        @if (string.IsNullOrEmpty(StreamingSession.Session.FotoHTMLSrc) == false)
        {
            <img src=@StreamingSession.Session.FotoHTMLSrc alt="Imagem de perfil" style="max-width: 50px;" />
        }
        else
        {
            <img src=@Url.Content("~/Content/Images/iconPerfil.png") alt="Imagem de perfil" />
        }
    </div>
    <div class="col-md-10">
        <p>
            @StreamingSession.Session.Nome
        </p>

        @if (Autenticacao.IsAdmin() == true)
        {
            <p>
                (ADMINISTRADOR)
            </p>
        }

        @if (Autenticacao.IsEstudante() == true)
        {
            <p>
                <label><b>Regime:</b></label>  @StreamingSession.Session.Regime
            </p>
            <p>
                <label><b>Número:</b></label> @StreamingSession.Session.Username
            </p>
        }

        @if (Autenticacao.IsTemporario() == true)
        {
            <p>
                (CONTA TEMPORÁRIA)
            </p>
        }

        @if (Autenticacao.IsTemporario() == true)
        {
            <a href=@Url.Action("EditCredenciaisTemporarias", "Session", new { username = StreamingSession.Session.Username })>
                O Meu Perfil
            </a>

            <span>|</span>
        }
        else if (Autenticacao.IsEstudante() == false)
        {
            <a href="https://www.campus.utad.pt/omeuperfil/Perfil/AlterarDadosPessoais">
                O Meu Perfil
            </a>

            <span>|</span>
        }

        <a href=@Url.Action("Logout", "Session")>
            <span class="fa fa-sign-out"></span>
            Terminar Sessão
        </a>
    </div>
</div>