Streaming/Controllers/AzureController.cs
namespace Streaming.Controllers
{
    using Microsoft.Rest.Azure;
    using Streaming.App_Start;
    using Streaming.Filters;
    using Streaming.Helpers;
    using Streaming.ViewModels;
    using StreamingAssemblies;
    using StreamingAssemblies.DataAccess;
    using StreamingAssemblies.Helpers.Azure;
    using StreamingAssemblies.Helpers.Azure.FileManagement;
    using StreamingAssemblies.Helpers.Misc;
    using StreamingAssemblies.Models.Azure;
    using StreamingAssemblies.Models.Azure.Logs;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;

    /// <summary>
    /// Defines the <see cref="AzureController" />.
    /// </summary>
    [StreamingLoggedIn]
    [StreamingAutorizacoes(GruposNomes = new string[] { StreamingAutorizacoesAttribute.VM_USER, StreamingAutorizacoesAttribute.VM_ADMIN })]
    public class AzureController : Controller
    {
        /// <summary>
        /// Defines the _defaultReturnTo.
        /// </summary>
        private string _defaultReturnTo = "Index";

        /// <summary>
        /// Defines the _azureService.
        /// </summary>
        private readonly AzureDb _azureService = new AzureDb(ConfigurationHelper.ConnectionStrings.StreamingDb);

        /// <summary>
        /// Defines the _streamingService.
        /// </summary>
        private readonly StreamingService _streamingService = new StreamingService(ConfigurationHelper.ConnectionStrings.StreamingDb);

        /// <summary>
        /// Defines the _logService.
        /// </summary>
        private readonly LogDb _logService = new LogDb(ConfigurationHelper.ConnectionStrings.StreamingDb);

        /// <summary>
        /// Gets the _authenticatedUserIupi.
        /// </summary>
        private string _authenticatedUserIupi => StreamingSession.Session.IUPI.ToString();

        /// <summary>
        /// The CreateVm.
        /// </summary>
        /// <returns>The <see cref="ActionResult"/>.</returns>
        [StreamingAutorizacoes(GruposNomes = new string[] { StreamingAutorizacoesAttribute.VM_ADMIN })]
        public ActionResult CreateVm()
        {
            return View();
        }

        /// <summary>
        /// The CreateVm.
        /// </summary>
        /// <param name="model">The model<see cref="AzureInsertVmModel"/>.</param>
        /// <returns>The <see cref="Task{ActionResult}"/>.</returns>
        [HttpPost]
        [StreamingAutorizacoes(GruposNomes = new string[] { StreamingAutorizacoesAttribute.VM_ADMIN })]
        public async Task<ActionResult> CreateVm(AzureInsertVmModel model)
        {
            try
            {
                ParameterExceptionHelper.ThrowIfArgumentIsNull(model, nameof(model));
                if (!model.IsValid)
                {
                    throw new ArgumentException("Model state is invalid", nameof(model));
                }

                //config file
                var configFileResult = await AzureFileManager.SaveAzureFileAsync(model.GetSubscriptionIdFromUrl(), model.TenantId, model.ApplicationId, model.ApplicationSecret);

                if (!configFileResult.Success)
                {
                    throw configFileResult.Exception;
                }

                var clientResult = AzureClientStore.AddAzureClient(configFileResult.Value);

                if (!clientResult.Success)
                {
                    throw clientResult.Exception;
                }

                var vmId = model.GetVmIdFromUrl();

                //try to get the VM to test the client
                var azureVmResult = await clientResult.Value.GetVirtualMachineAsync(vmId);

                if (!azureVmResult.Success)
                {
                    AzureFileManager.DeleteAzureFile(configFileResult.Value);
                    throw azureVmResult.Exception;
                }

                var newVm = new AzureVirtualMachine()
                {
                    ConfigFilePath = configFileResult.Value,
                    PluginUrl = model.PluginUrl,
                    VmId = vmId,
                    VmName = azureVmResult.Value.Name,
                    Alias = model.Alias
                };

                var insertedResult = await _azureService.EditVirtualMachineAsync(newVm, _authenticatedUserIupi);

                if (insertedResult.Success)
                {
                    SetSuccessMessage($"A máquina virtual {newVm.DisplayName} foi adicionada com sucesso.");
                }
                else
                {
                    throw insertedResult.Exception;
                }
            }
            catch (Exception ex)
            {
                await _logService.Log(ex, _authenticatedUserIupi);
                SetErrorMessage("Ocorreu um erro ao adicionar a máquina virtual. Reveja os dados inseridos, permissões no Azure ou tente mais tarde.");
            }

            return ReturnToReferral(Request);
        }

        /// <summary>
        /// The EditVm.
        /// </summary>
        /// <param name="id">The id<see cref="int"/>.</param>
        /// <returns>The <see cref="ActionResult"/>.</returns>
        [StreamingAutorizacoes(GruposNomes = new string[] { StreamingAutorizacoesAttribute.VM_ADMIN })]
        public async Task<ActionResult> EditVm(int id)
        {
            AzureUpdateVmModel model = null;

            try
            {
                ParameterExceptionHelper.ThrowIfArgumentIsNull(id, 0);

                var vmResult = await _azureService.GetVirtualMachineAsync(id);

                if (!vmResult.Success)
                {
                    if (vmResult.Exception != null)
                    {
                        throw vmResult.Exception;
                    }
                    else
                    {
                        throw new ArgumentException($"VM with id {id} not found.");
                    }
                }

                model = await AzureUpdateVmModel.FromAzureVirtualMachineAsync(vmResult.Value);
            }
            catch (Exception ex)
            {
                await _logService.Log(ex, _authenticatedUserIupi);
                SetErrorMessage("Ocorreu um erro ao editar a máquina virtual.");

                return ReturnToReferral(Request, "Manage");
            }

            return View(model);
        }

        /// <summary>
        /// The EditVm.
        /// </summary>
        /// <param name="model">The model<see cref="AzureInsertVmModel"/>.</param>
        /// <returns>The <see cref="Task{ActionResult}"/>.</returns>
        [HttpPost]
        [StreamingAutorizacoes(GruposNomes = new string[] { StreamingAutorizacoesAttribute.VM_ADMIN })]
        public async Task<ActionResult> EditVm(AzureUpdateVmModel model)
        {
            try
            {
                ParameterExceptionHelper.ThrowIfArgumentIsNull(model, nameof(model));
                if (!model.IsValid)
                {
                    throw new ArgumentException("Model state is invalid", nameof(model));
                }

                var vm = await _azureService.GetVirtualMachineAsync(model.Id);

                if (!vm.Success)
                {
                    throw vm.Exception;
                }

                //config file
                var configFileResult = await AzureFileManager.SaveAzureFileAsync(model.GetSubscriptionIdFromUrl(), model.TenantId, model.ApplicationId, model.ApplicationSecret);

                if (!configFileResult.Success)
                {
                    throw configFileResult.Exception;
                }

                var clientResult = AzureClientStore.AddAzureClient(configFileResult.Value);

                if (!clientResult.Success)
                {
                    AzureFileManager.DeleteAzureFile(configFileResult.Value);
                    throw clientResult.Exception;
                }

                var vmId = model.GetVmIdFromUrl();

                //try to get the VM to test the client
                var azureVmResult = await clientResult.Value.GetVirtualMachineAsync(vmId);

                if (!azureVmResult.Success)
                {
                    AzureFileManager.DeleteAzureFile(configFileResult.Value);
                    throw azureVmResult.Exception;
                }

                var newVm = new AzureVirtualMachine()
                {
                    Id = model.Id,
                    ConfigFilePath = configFileResult.Value,
                    VmAzureUrl = model.AzureVmUrl,
                    PluginUrl = model.PluginUrl,
                    VmId = vmId,
                    VmName = azureVmResult.Value.Name,
                    Alias = model.Alias
                };

                var editedResult = await _azureService.EditVirtualMachineAsync(newVm, _authenticatedUserIupi);

                if (editedResult.Success)
                {
                    SetSuccessMessage($"A máquina virtual {newVm.DisplayName} foi editada com sucesso.");
                }
                else
                {
                    throw editedResult.Exception;
                }

                //delete old config file
                AzureFileManager.DeleteAzureFile(vm.Value.ConfigFilePath);
            }
            catch (Exception ex)
            {
                await _logService.Log(ex, _authenticatedUserIupi);
                SetErrorMessage("Ocorreu um erro ao editar a máquina virtual. Reveja os dados inseridos, permissões no Azure ou tente mais tarde.");
            }

            return ReturnToReferral(Request);
        }

        /// <summary>
        /// The Stop.
        /// </summary>
        /// <param name="id">The id<see cref="string"/>.</param>
        /// <returns>The <see cref="Task{ActionResult}"/>.</returns>
        [HttpPost]
        [StreamingAutorizacoes(GruposNomes = new string[] { StreamingAutorizacoesAttribute.VM_ADMIN })]

Streaming/Views/Azure/CreateVm.cshtml
@using Streaming.App_Start;

@model StreamingAssemblies.Models.Azure.AzureInsertVmModel

@{
    ViewBag.Title = "Adicionar servidor";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.Label("Nome personalizado", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("URL de gestão no portal do Azure", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AzureVmUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AzureVmUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Directory (tenant) ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenantId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenantId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Application (client) ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ApplicationId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ApplicationId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Application (client) secret", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ApplicationSecret, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ApplicationSecret, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("URL do plugin de vídeo", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PluginUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PluginUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a class="btn btn-danger" href="@Url.Action("Manage", "Azure")">
                <span class="fa fa-arrow-circle-left"></span>
                Cancelar
            </a>
            <input type="submit" value="Criar" class="btn btn-primary" />
        </div>
    </div>
</div>
}

Streaming/Views/Azure/DeleteVmPartial.cshtml
@model StreamingAssemblies.Models.Azure.AzureStopDeleteVmModel

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Tem a certeza?</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Nome")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VmName)
        </dd>

    </dl>
</div>
<div class="modal-footer">
    @using (Html.BeginForm("Delete", "Azure", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(x => Model.Id)

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" />
        </div>
    }
</div>

Streaming/Views/Azure/EditVm.cshtml
@using Streaming.App_Start;

@model StreamingAssemblies.Models.Azure.AzureUpdateVmModel

@{
    ViewBag.Title = "Adicionar servidor";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Id)

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.Label("Nome personalizado", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("URL de gestão no portal do Azure", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AzureVmUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AzureVmUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Directory (tenant) ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenantId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenantId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Application (client) ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ApplicationId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ApplicationId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Application (client) secret", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ApplicationSecret, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ApplicationSecret, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("URL do plugin de vídeo", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PluginUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PluginUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a class="btn btn-danger" href="@Url.Action("Manage", "Azure")">
                <span class="fa fa-arrow-circle-left"></span>
                Cancelar
            </a>
            <input type="submit" value="Editar" class="btn btn-primary" />
        </div>
    </div>
</div>
}

Streaming/Views/Azure/Index.cshtml
@model IEnumerable<StreamingAssemblies.Models.Azure.AzureVirtualMachine>

@{
    ViewBag.Title = "Servidores de streaming";
}

<h2>@ViewBag.Title</h2>

<hr />

<p>
    <a class="btn btn-primary" href="javascript:location.reload(true);">
        <span class="fa fa-refresh"></span>
        Atualizar
    </a>
</p>

@if (Model.Count() > 0)
{
    <table id="vms" class="table">
        <tr>
            <th>
                @Html.DisplayName("Nome")
            </th>
            <th>
                @Html.DisplayName("Estado")
            </th>
            <th>
                @Html.DisplayName("URL do plugin de vídeo")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
    <tr class="vmLine" data-id="@item.Id" data-name="@item.DisplayName">
        <td>
            @Html.DisplayFor(modelItem => item.DisplayName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PowerStateString)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PluginUrl)
        </td>
        <td style="text-align: right">
            <a class="btn btn-primary @(@item.CanStart ? "" : "disabled")" href="@Url.Action("Start", "Azure", new { id = item.Id, returnTo = "Index" })">
                <span class="fa fa-play"></span>
                Iniciar
            </a>
            <button class="btn btn-danger @(@item.CanStop ? "" : "disabled")" data-toggle="modal" data-target="#stopVmModal">
                <span class="fa fa-stop"></span>
                Parar
            </button>
        </td>
    </tr>
        }

    </table>

    <div class="modal fade" id="stopVmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div id="stopVmModalContent" class="modal-content">

            </div>
        </div>
    </div>
}
else
{
    <p>
        <b>Não existem máquinas virtuais para apresentar.</b>
    </p>
}

<script>
    $(document).ready(function () {
        let getVmLine = function (btn) {
            if (btn) {
                return $(btn).closest(".vmLine");
            }

            return null;
        }

        $("#stopVmModal").on("show.bs.modal", function (event) {
            let stopVmModalButton = $(event.relatedTarget);

            if (stopVmModalButton.hasClass("disabled")) {
                event.preventDefault();
                return;
            }

            let vmLine = getVmLine(stopVmModalButton);

            let vmId = vmLine.data("id");
            let vmName = vmLine.data("name");

            if (vmId) {
                $("#stopVmModalContent").load("@Url.Action("LoadStopVmPartial", "Azure")", { id: vmId, name: vmName, returnTo: "Index" });
            }
        });

        $(".startBtn").on("click", function (event) {
            let btn = $(this);

            if (btn.hasClass("disabled")) {
                event.preventDefault();
                return;
            }

            let vmLine = getVmLine(btn);

            $.post("@Url.Action("Start", "Azure")", { id: vmLine.data().id }, function () {
                location.reload();
            });
        });
    });
</script>

Streaming/Views/Azure/Manage.cshtml
@model IEnumerable<StreamingAssemblies.Models.Azure.AzureVirtualMachine>

@{
    ViewBag.Title = "Gerir servidores";
}

<h2>@ViewBag.Title</h2>

<hr />

<p>
    <a class="btn btn-primary" href="@Url.Action("CreateVm", "Azure")">
        <span class="fa fa-plus"></span>
        Adicionar máquina virtual
    </a>

    <a class="btn btn-primary" href="javascript:location.reload(true);">
        <span class="fa fa-refresh"></span>
        Atualizar
    </a>
</p>

@if (Model.Count() > 0)
{
    <table id="vms" class="table">
        <tr>
            <th>
                @Html.DisplayName("Nome")
            </th>
            <th>
                @Html.DisplayName("Estado")
            </th>
            <th>
                @Html.DisplayName("URL do plugin de vídeo")
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class="vmLine" data-id="@item.Id" data-name="@item.DisplayName">
                <td>
                    @Html.DisplayFor(modelItem => item.DisplayName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PowerStateString)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PluginUrl)
                </td>
                <td>
                    @if (item.IsActive)
                    {
                        <a class="btn btn-primary btn-static btn-info">
                            <span class="fa fa-check-circle"></span>
                            Ativo
                        </a>
                    }
                    else
                    {
                        <a class="btn btn-primary btn-static btn-danger">
                            <span class="fa fa-times-circle"></span>
                            Inativo
                        </a>
                    }
                </td>
                <td style="text-align: right">
                    <a class="btn btn-primary @(@item.CanStart ? "" : "disabled")" href="@Url.Action("Start", "Azure", new { id = item.Id, returnTo = "Manage" })">
                        <span class="fa fa-play"></span>
                        Iniciar
                    </a>
                    <button class="btn btn-danger @(@item.CanStop ? "" : "disabled")" data-toggle="modal" data-target="#stopVmModal">
                        <span class="fa fa-stop"></span>
                        Parar
                    </button>
                </td>
                <td style="text-align: right">
                    <a class="btn btn-primary" href="@Url.Action("EditVm", "Azure", new { id = item.Id })">
                        <span class="fa fa-edit"></span>
                        Editar
                    </a>
                    @if (item.IsActive)
                    {
                        <a class="btn btn-primary btn-danger" href="@Url.Action("SetInactive", "Azure", new { id = item.Id })">
                            <span class="fa fa-times-circle"></span>
                            Desativar
                        </a>
                    }
                    else
                    {
                        <a class="btn btn-primary btn-info" href="@Url.Action("SetActive", "Azure", new { id = item.Id })">
                            <span class="fa fa-check-circle"></span>
                            Ativar
                        </a>
                    }
                    <button class="btn btn-danger" data-toggle="modal" data-target="#deleteVmModal">
                        <span class="fa fa-trash"></span>
                        Eliminar
                    </button>
                </td>
            </tr>
        }

    </table>

    <div class="modal fade" id="stopVmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div id="stopVmModalContent" class="modal-content">

            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteVmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div id="deleteVmModalContent" class="modal-content">

            </div>
        </div>
    </div>
}
else
{
    <p>
        <b>Não existem máquinas virtuais para apresentar.</b>
    </p>
}

<script>
    $(document).ready(function () {
        let getVmLine = function (btn) {
            if (btn) {
                return $(btn).closest(".vmLine");
            }

            return null;
        }

        $("#stopVmModal").on("show.bs.modal", function (event) {
            let stopVmModalButton = $(event.relatedTarget);

            if (stopVmModalButton.hasClass("disabled")) {
                event.preventDefault();
                return;
            }

            let vmLine = getVmLine(stopVmModalButton);

            let vmId = vmLine.data("id");
            let vmName = vmLine.data("name");

            if (vmId) {
                $("#stopVmModalContent").load("@Url.Action("LoadStopVmPartial", "Azure")", { id: vmId, name: vmName, returnTo: "Manage" });
            }
        });


        $("#deleteVmModal").on("show.bs.modal", function (event) {
            let stopVmModalButton = $(event.relatedTarget);

            if (stopVmModalButton.hasClass("disabled")) {
                event.preventDefault();
                return;
            }

            let vmLine = getVmLine(stopVmModalButton);

            let vmId = vmLine.data("id");
            let vmName = vmLine.data("name");

            if (vmId) {
                $("#deleteVmModalContent").load("@Url.Action("LoadDeleteVmPartial", "Azure")", { id: vmId, name: vmName, returnTo: "Manage" });
            }
        });

        $(".startBtn").on("click", function (event) {
            let btn = $(this);

            if (btn.hasClass("disabled")) {
                event.preventDefault();
                return;
            }

            let vmLine = getVmLine(btn);

            $.post("@Url.Action("Start", "Azure")", { id: vmLine.data().id }, function () {
                location.reload();
            });
        });
    });
</script>

Streaming/Views/Azure/StopVmPartial.cshtml
@model StreamingAssemblies.Models.Azure.AzureStopDeleteVmModel

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Tem a certeza?</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Nome")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VmName)
        </dd>

    </dl>
</div>
<div class="modal-footer">
    @using (Html.BeginForm("Stop", "Azure", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(x => Model.Id)

        <div class="form-actions no-color">
            <input type="submit" value="Parar" class="btn btn-danger" />
        </div>
    }
</div>

Streaming/Views/Azure/VmLogs.cshtml
@model IEnumerable<Streaming.ViewModels.AzureLogViewModel>

@{
    ViewBag.Title = "Logs";
}

<h2>@ViewBag.Title</h2>

<hr />

<p>
    <a class="btn btn-primary" href="javascript:location.reload(true);">
        <span class="fa fa-refresh"></span>
        Atualizar
    </a>
</p>

@if (Model.Count() > 0)
{
    <table id="vms" class="table">
        <tr>
            <th>
                @Html.DisplayName("Username")
            </th>
            <th>
                @Html.DisplayName("Nome completo")
            </th>
            <th>
                @Html.DisplayName("Data")
            </th>
            <th>
                @Html.DisplayName("Mensagem")
            </th>
            <th>
                @Html.DisplayName("Nome da VM")
            </th>
            <th>
                @Html.DisplayName("Ação")
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class="vmLine">
                <td>
                    @Html.DisplayFor(modelItem => item.Username)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Message)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VmName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Action)
                </td>
            </tr>
        }

    </table>
}
else
{
    <p>
        <b>Não existem logs para apresentar.</b>
    </p>
}