Streaming/ViewModels/LoadEstudantePerfilViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Streaming.ViewModels
{
    public class LoadEstudantePerfilViewModel
    {
        public string Nome { get; set; }
        public string CodCurso { get; set; }
        public string Curso { get; set; }
        public string NomeAcesso { get; set; }

        public LoadEstudantePerfilViewModel()
        {
            Nome = "";
            CodCurso = "";
            Curso = "";
            NomeAcesso = "";
        }
    }
}

Streaming/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using StreamingAssemblies.Models;

namespace Streaming.ViewModels
{
    public class LoginViewModel
    {
        public LoginCredenciais LoginCredenciais { get; set; }
        public LoginCredenciais LoginCredenciaisTemporarias { get; set; }
        public string EmailRecuperarCredenciaisTemporarias { get; set; }

        public LoginViewModel()
        {
            LoginCredenciais = new LoginCredenciais();
            LoginCredenciaisTemporarias = new LoginCredenciais();
            EmailRecuperarCredenciaisTemporarias = "";
        }
    }
}

Streaming/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Net;
using System.Linq;

using System.Configuration;
using System.Security.Cryptography;
using System.Threading;
using System.Globalization;

using CaptchaMvc.HtmlHelpers;

using Streaming.App_Start;
using Streaming.Clients;
using Streaming.Filters;
using Streaming.Helpers;
using Streaming.ViewModels;

using StreamingAssemblies.DataAccess;
using StreamingAssemblies.Models;
using StreamingAssemblies.Models.Streaming;
using StreamingAssemblies.Models.QuoVadis.RCU;

namespace Streaming.Controllers
{
    public class SessionController : BaseController
    {
        private readonly StreamingService _streamingService = new StreamingService(ConfigurationManager.ConnectionStrings["streamingDBString"].ConnectionString);

        private readonly IUTADClient _iUTADClient = new IUTADClient();
        private readonly RCUClient _rcuClient = new RCUClient();

        [StreamingLoggedOff]
        public ActionResult Login()
        {
            return View();
        }

        // Esta é a função principal de autenticação
        // Verifica credenciais, obtém cargos e perfis do login e, com esses dados, verifica as autorizações que o login possui na aplicação
        // Adicionalmente regista o acesso do login na tabela de registo da base de dados do Streaming
        [StreamingUTAD]
        [StreamingLoggedOff]
        [HttpPost]
        public ActionResult Login(LoginViewModel loginViewModel)
        {
            // Primeiro valida os campos do nome de utilizador e da palavra-passe
            if (string.IsNullOrEmpty(loginViewModel.LoginCredenciais.Username) == true)
            {
                ModelState.AddModelError("LoginCredenciais.Username", "Tem de introduzir um nome de utilizador válido!");
            }

            if(string.IsNullOrEmpty(loginViewModel.LoginCredenciais.Password) == true)
            {
                ModelState.AddModelError("LoginCredenciais.Password", "Tem de introduzir uma palavra-passe válida!");
            }

            if(ModelState.IsValid == true)
            {
                Login login = new Login();

                // Dependendo do valor da flag de simulação de autenticação presente no Web.config, usa diferentes mecanismos para autenticar o login
                if (Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.UTAD.Simul"]) == true)
                {
                    // Usa serviços Web de simulação para autenticar o login
                    login = AutenticacaoSimul.AutenticarLoginWSSimul(loginViewModel.LoginCredenciais.Username, loginViewModel.LoginCredenciais.Password);
                }
                else
                {
                    // Usa o serviço Web real de autenticação, que inclui o mecanismo de autenticação por impersonação
                    // Neste mecanismo, um administrador pode autenticar-se como se fosse um utilizador à sua escolha, e ver o que esse utilizador vê no Streaming
                    bool canAutenticarLoginWS = true;

                    if (loginViewModel.LoginCredenciais.Username.Contains(";") == true)
                    {
                        // Assumindo que o login introduzido se encontra na estrutura "administrador;login", separa o login em dois
                        string[] userAdminImpersonacao = loginViewModel.LoginCredenciais.Username.Split(';');

                        string adminImpersonacao = userAdminImpersonacao[0];
                        string userImpersonacao = userAdminImpersonacao[1];

                        if (string.IsNullOrEmpty(adminImpersonacao) == false && string.IsNullOrEmpty(userImpersonacao) == false)
                        {
                            canAutenticarLoginWS = Autenticacao.IsLoginAdmin(adminImpersonacao);
                        }
                        else
                        {
                            canAutenticarLoginWS = false;
                        }
                    }

                    if (canAutenticarLoginWS == true)
                    {
                        login = _iUTADClient.Auth(loginViewModel.LoginCredenciais.Username, loginViewModel.LoginCredenciais.Password);
                    }
                }

                // Se o login tiver sido autenticado com sucesso, procede para a função de carregamento do login
                if (login != null && login.IUPI != null && login.IUPI != new Guid())
                {
                    // -1 - Login não possui permissões
                    // 0 - Ocorreu um erro ao carregar o login
                    // 1 - Login carregado com sucesso
                    // 2 - Login carregado com sucesso (estudante)
                    int success = LoadLogin(login);

                    switch (success)
                    {
                        case -1:
                            TempData["error"] = "Não possui permissões para aceder a esta aplicação!";

                            return View();

                        case 0:
                            TempData["error"] = "Ocorreu um erro ao carregar a informação pessoal!";

                            return View();

                        case 1:
                            var symbols = HttpHelper.GetLanguageSymbols(Request);
                            if (LoadLoginLinguagem(symbols) == true)
                            {
                                return RedirectToAction("Index", "Home");
                            }
                            else
                            {
                                TempData["error"] = "Ocorreu um erro ao carregar informação!";

                                return View();
                            }

                        case 2:
                            return RedirectToAction("LoadEstudantePerfil", new { iupi = login.IUPI });

                        default:
                            break;
                    }
                }
                else
                {
                    // Caso contrário, se o login não tiver sido autenticado com sucesso, significa que as credenciais introduzidas estão erradas
                    // Portanto apresenta uma mensagem de erro
                    TempData["error"] = "Credenciais inválidas! Por favor verifique as credenciais introduzidas e tente de novo.";
                }
            }
            else
            {
                // Caso o utilizador não tenha introduzido o nome de utilizador ou a palavra-passe, apresenta uma mensagem de erro
                TempData["error"] = "Tem de preencher todos os campos!";
            }

            return View();
        }

        [StreamingUTADLoginAdmin]
        [StreamingLoggedOff]
        public ActionResult LoginAdmin()
        {
            return View();
        }

        [StreamingUTADLoginAdmin]
        [StreamingLoggedOff]
        [HttpPost]
        public ActionResult LoginAdmin(LoginViewModel loginViewModel)
        {
            // Primeiro valida os campos do nome de utilizador e da palavra-passe
            if (string.IsNullOrEmpty(loginViewModel.LoginCredenciais.Username) == true)
            {
                ModelState.AddModelError("LoginCredenciais.Username", "Tem de introduzir um nome de utilizador válido!");
            }

            if (string.IsNullOrEmpty(loginViewModel.LoginCredenciais.Password) == true)
            {
                ModelState.AddModelError("LoginCredenciais.Password", "Tem de introduzir uma palavra-passe válida!");
            }

            if (ModelState.IsValid == true)
            {
                Login login = new Login();

                // Primeiro verifica se as credenciais introduzidas correspondem a um administrador válido do Streaming
                bool isAdmin = false;

                if (loginViewModel.LoginCredenciais.Username.Contains(";") == true)
                {
                    // Assumindo que o login introduzido se encontra na estrutura "administrador;login", separa o login em dois
                    string[] userAdminImpersonacao = loginViewModel.LoginCredenciais.Username.Split(';');

                    string adminImpersonacao = userAdminImpersonacao[0];
                    string userImpersonacao = userAdminImpersonacao[1];

                    if (string.IsNullOrEmpty(adminImpersonacao) == false && string.IsNullOrEmpty(userImpersonacao) == false)
                    {
                        isAdmin = Autenticacao.IsLoginAdmin(adminImpersonacao);
                    }
                }
                else
                {
                    isAdmin = Autenticacao.IsLoginAdmin(loginViewModel.LoginCredenciais.Username);
                }

                if (isAdmin == true)
                {
                    // Dependendo do valor da flag de simulação de autenticação presente no Web.config, usa diferentes mecanismos para autenticar o login
                    if (Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.UTAD.Simul"]) == true)
                    {
                        // Usa serviços Web de simulação para autenticar o login
                        login = AutenticacaoSimul.AutenticarLoginWSSimul(loginViewModel.LoginCredenciais.Username, loginViewModel.LoginCredenciais.Password);
                    }
                    else
                    {
                        // Usa o serviço Web real de autenticação, que inclui o mecanismo de autenticação por impersonação
                        // Neste mecanismo, um administrador pode autenticar-se como se fosse um utilizador à sua escolha, e ver o que esse utilizador vê no Streaming
                        login = _iUTADClient.Auth(loginViewModel.LoginCredenciais.Username, loginViewModel.LoginCredenciais.Password);
                    }

                    // Se o login tiver sido autenticado com sucesso, procede para a função de carregamento do login

Streaming/Views/Session/EditCredenciaisTemporarias.cshtml
@using Streaming.App_Start;

@model StreamingAssemblies.Models.QuoVadis.RCU.CredenciaisTemporariasUpdate

@{
    ViewBag.Title = "O Meu Perfil";
}

<h2>O Meu Perfil</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Dados do Perfil</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Endereço de E-mail", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Idioma de Apresentação", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DefaultLanguage, new SelectList(StreamingSession.Session.Linguagens, "Symbol", "Titulo"), "Por favor seleccione o idioma de apresentação", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DefaultLanguage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a class="btn btn-danger" href="@Url.Action("Index", "Home")">
                    <span class="fa fa-arrow-circle-left"></span>
                    Cancelar
                </a>
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

Streaming/Views/Session/LoadEstudantePerfil.cshtml
@model IEnumerable<Streaming.ViewModels.LoadEstudantePerfilViewModel>

@{
    ViewBag.Title = "Escolher Matrícula";
}

<br>
<br>
<br>
<br>
<br>
<br>

<div class="row">
    <div class="offset-md-4 col-md-4">
        <div class="card border-info">
            <div class="card-header text-info">
                <h3>Escolher Matrícula</h3>
            </div>
            <div class="card-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-12">
                            <img id="utad-logo" src="~/Content/Images/logo_utad_completo_preto.png" style="width: 50%">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            @foreach (var item in Model)
                            {
                                using (Html.BeginForm("LoadEstudantePerfil", "Session"))
                                {
                                    @Html.AntiForgeryToken()

                                    @Html.Hidden("Nome", item.Nome)
                                    @Html.Hidden("CodCurso", item.CodCurso)
                                    @Html.Hidden("NomeAcesso", item.NomeAcesso)

                                    <div class="form-actions no-color">
                                        <input type="submit" value="@item.Curso" class="list-group-item list-group-item-action" />
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Streaming/Views/Session/Login.cshtml
@using System.Configuration;

@model Streaming.ViewModels.LoginViewModel

@{
    ViewBag.Title = "Iniciar Sessão";
}

<br>
<br>
<br>
<br>
<br>
<br>

<div class="row">
    @if (Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.UTAD"]) == true)
    {
        <div id="authUTADCard" class="offset-md-1 col-md-4" style="display: none">
            <div class="card border-info">
                <div class="card-header text-info">
                    <h3>Autenticação com uma conta da UTAD <span style="font-size: 13px">(*utad.pt/*utad.eu)</span></h3>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <div class="col-md-12">
                                    <img id="ctl00_idDigital" src="~/Content/Images/logo_utad_completo_preto.png" style="width: 50%">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.LoginCredenciais.Username, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nome de Utilizador (sem @utad.pt ou @utad.eu)" } })
                                    @Html.ValidationMessageFor(model => model.LoginCredenciais.Username, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    @Html.PasswordFor(model => model.LoginCredenciais.Password, new { @class = "form-control", @placeholder = "Palavra-Passe" })
                                    @Html.ValidationMessageFor(model => model.LoginCredenciais.Password, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="submit" value="Entrar" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    }

    @if (Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.CredenciaisTemporarias"]) == true)
    {
        <div id="authCredenciaisTemporariasCard" class="offset-md-1 col-md-5" style="display: none">
            <div class="card border-info">
                <div class="card-header text-info">
                    @if (Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.UTAD"]) == true)
                    {
                        <h3>Autentique-se aqui se não tem uma conta da UTAD, ou criou uma conta nesta aplicação</h3>
                    }
                    else
                    {
                        <h3>Autenticação</h3>
                    }
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("LoginCredenciaisTemporarias", "Session"))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.LoginCredenciaisTemporarias.Username, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nome de Utilizador" } })
                                    @Html.ValidationMessageFor(model => model.LoginCredenciaisTemporarias.Username, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    @Html.PasswordFor(model => model.LoginCredenciaisTemporarias.Password, new { @class = "form-control", @placeholder = "Palavra-Passe" })
                                    @Html.ValidationMessageFor(model => model.LoginCredenciaisTemporarias.Password, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="submit" value="Entrar" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }

                    @if (Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.CredenciaisTemporarias.Registo"]) == true)
                    {
                        <div class="form-group">
                            <div class="col-md-12">
                                <hr />
                                <h6>Não tem uma conta?</h6>
                                <h6>Clique aqui neste botão para efetuar o seu registo temporário.</h6>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.ActionLink("Efetuar Registo", "RegistarCredenciaisTemporarias", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    }

                    @if (Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.CredenciaisTemporarias.Recuperacao"]) == true)
                    {
                        using (Html.BeginForm("RecuperarCredenciaisTemporarias", "Session"))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <hr />
                                        <h6>Esqueceu-se da sua palavra-passe?</h6>
                                        <h6>Introduza aqui o seu endereço de e-mail, ou o seu nome de utilizador, para receber um e-mail de recuperação na sua caixa de correio electrónico.</h6>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.EmailRecuperarCredenciaisTemporarias, new { htmlAttributes = new { @class = "form-control", @placeholder = "Endereço de e-mail/Nome de utilizador" } })
                                        @Html.ValidationMessageFor(model => model.EmailRecuperarCredenciaisTemporarias, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <input type="submit" value="Enviar E-mail de Recuperação" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        @if(Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.UTAD"]) == true && Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.CredenciaisTemporarias"]) == false)
        {
            <text>
                $("#authUTADCard").removeClass();
                $("#authUTADCard").addClass("offset-md-4 col-md-4");
            </text>
        }
        else if (Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.UTAD"]) == false && Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.CredenciaisTemporarias"]) == true) {
            <text>
                $("#authCredenciaisTemporariasCard").removeClass();
                $("#authCredenciaisTemporariasCard").addClass("offset-md-4 col-md-4");
            </text>
        }

        $("#authUTADCard").show();
        $("#authCredenciaisTemporariasCard").show();
    });
</script>

Streaming/Views/Session/LoginAdmin.cshtml
@model Streaming.ViewModels.LoginViewModel

@{
    ViewBag.Title = "Iniciar Sessão - Administradores";
}

<br>
<br>
<br>
<br>
<br>
<br>

<div class="row">
    <div class="offset-md-4 col-md-4">
        <div class="card border-info">
            <div class="card-header text-info">
                <h3>Autenticação - Administradores <span style="font-size: 13px">(*utad.pt/*utad.eu)</span></h3>
            </div>
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.LoginCredenciais.Username, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nome de Utilizador (sem @utad.pt ou @utad.eu)" } })
                                @Html.ValidationMessageFor(model => model.LoginCredenciais.Username, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.PasswordFor(model => model.LoginCredenciais.Password, new { @class = "form-control", @placeholder = "Palavra-Passe" })
                                @Html.ValidationMessageFor(model => model.LoginCredenciais.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Entrar" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Streaming/Views/Session/RegistarCredenciaisTemporarias.cshtml
@using CaptchaMvc.HtmlHelpers;

@using Streaming.App_Start;

@model StreamingAssemblies.Models.RegistoCredenciaisTemporarias

@{
    ViewBag.Title = "Efetuar Registo";
}

<br>
<br>
<br>
<br>
<br>
<br>

<div class="row">
    <div class="offset-md-4 col-md-4">
        <div class="card border-info">
            <div class="card-header text-info">
                <h3>Efetuar Registo</h3>
            </div>
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div class="col-md-12">
                                <img id="utad-logo" src="~/Content/Images/logo_utad_completo_preto.png" style="width: 50%">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nome" } })
                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Endereço de e-mail" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.EmailRepeticao, new { htmlAttributes = new { @class = "form-control", @placeholder = "Repetir endereço de e-mail" } })
                                @Html.ValidationMessageFor(model => model.EmailRepeticao, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.DropDownListFor(model => model.DefaultLanguage, new SelectList(StreamingSession.Session.Linguagens, "Symbol", "Titulo"), "Por favor seleccione o idioma de apresentação", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DefaultLanguage, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.Captcha("Gerar Nova Imagem", "Por favor introduza os caracteres que aparecem na imagem", 6, new CaptchaMvc.Models.ParameterModel("class", "form-control") )
                                @Html.ValidationMessage("Captcha", "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                <a class="btn btn-danger" href="@Url.Action("Login", "Session")">
                                    <span class="fa fa-arrow-circle-left"></span>
                                    Cancelar
                                </a>
                                <input type="submit" value="Registar" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>